<a href="https://colab.research.google.com/github/danish2k04/Getting-into-Pytorch-Deep-Learning/blob/main/00_pytorch_fundametals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.10.0+cu128


Introduction To Tensor

Creating Tensor

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [ ]:
TENSOR2 = torch.tensor([[[2,4,6],[5,5,5],[4,4,4]],[[2,2,2],[7,7,7],[8,8,8]]])
TENSOR2

tensor([[[2, 4, 6],
         [5, 5, 5],
         [4, 4, 4]],

        [[2, 2, 2],
         [7, 7, 7],
         [8, 8, 8]]])

In [ ]:
TENSOR2.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR2.ndim

3

In [ ]:
TENSOR2[0]

tensor([[2, 4, 6],
        [5, 5, 5],
        [4, 4, 4]])

In [ ]:
#random tensors
#create a random tensor of size (2,3)
random_tensor = torch.rand(2,3)


In [ ]:
random_tensor

tensor([[0.0268, 0.9117, 0.3021],
        [0.2102, 0.2021, 0.9787]])

In [ ]:
random_image_size_tensor = torch.rand(size = (3, 224, 224))
random_image_size_tensor

tensor([[[0.2862, 0.0441, 0.5803,  ..., 0.2369, 0.1419, 0.7110],
         [0.0245, 0.7595, 0.3553,  ..., 0.4685, 0.1559, 0.0826],
         [0.4489, 0.4559, 0.5465,  ..., 0.5204, 0.2554, 0.0077],
         ...,
         [0.4846, 0.3910, 0.2143,  ..., 0.9876, 0.5032, 0.9531],
         [0.4870, 0.7355, 0.7371,  ..., 0.7349, 0.5805, 0.1842],
         [0.7015, 0.0314, 0.3230,  ..., 0.0919, 0.4136, 0.6523]],

        [[0.2381, 0.1792, 0.3070,  ..., 0.1408, 0.4095, 0.6264],
         [0.6567, 0.4588, 0.6029,  ..., 0.3369, 0.9826, 0.2384],
         [0.0663, 0.1950, 0.0187,  ..., 0.2483, 0.0264, 0.8859],
         ...,
         [0.3665, 0.5966, 0.8562,  ..., 0.4352, 0.2293, 0.0620],
         [0.3652, 0.6095, 0.9836,  ..., 0.7081, 0.0211, 0.2970],
         [0.2333, 0.4297, 0.8562,  ..., 0.2682, 0.4304, 0.3748]],

        [[0.3738, 0.1577, 0.0611,  ..., 0.6169, 0.8898, 0.1762],
         [0.3538, 0.8294, 0.0588,  ..., 0.2087, 0.6962, 0.9971],
         [0.2934, 0.6878, 0.7386,  ..., 0.6574, 0.6806, 0.

In [ ]:
#cretae a tensor of all zeros
zeros = torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
random_tensor

tensor([[0.0268, 0.9117, 0.3021],
        [0.2102, 0.2021, 0.9787]])

In [ ]:
#create a tensor of ones
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#creating a range of tensors
one_to_ten_tensor = torch.arange(1,10+1)
one_to_ten_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating a tesnor like
ten_zeroes = torch.zeros_like(input=one_to_ten_tensor)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

tensor datatypes

In [ ]:
float_32 = torch.tensor([3.0, 4.0, 5.0],
                        dtype = None,
                        device = None,
                        requires_grad = False)
float_32

tensor([3., 4., 5.])

In [ ]:
float_32.dtype

torch.float32

In [ ]:
float_16 = float_32
float_16

tensor([3., 4., 5.])

In [ ]:
float_16 * float_32

tensor([ 9., 16., 25.])

In [ ]:
some_tensor = torch.rand([3,4], device = None, dtype = torch.float16, requires_grad = False)

In [ ]:
some_tensor

tensor([[0.0303, 0.1138, 0.8081, 0.1821],
        [0.5176, 0.9971, 0.8779, 0.1753],
        [0.7437, 0.7700, 0.0952, 0.8989]], dtype=torch.float16)

In [ ]:
print(f"Datatype: {some_tensor.dtype}")
print(f"shape: {some_tensor.shape}")
print(f"device: {some_tensor.device}")

Datatype: torch.float16
shape: torch.Size([3, 4])
device: cpu


# Manipulating Tensors

In [ ]:
#create a tensor
tensor = torch.tensor([1,3,3])
tensor + 10

tensor([11, 13, 13])

In [ ]:
tensor * 10



tensor([10, 30, 30])

In [ ]:
tensor - 10

tensor([-9, -7, -7])

In [ ]:
MATRIX_1 = torch.tensor([[3, 5], [7, 8]])
MATRIX_1 * 10

tensor([[30, 50],
        [70, 80]])

In [ ]:
torch.matmul(MATRIX_1, MATRIX_1)

tensor([[44, 55],
        [77, 99]])

In [ ]:
MATRIX_1

tensor([[3, 5],
        [7, 8]])

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.8461, 0.8489, 1.2300],
        [0.1314, 0.4934, 0.5760],
        [0.3652, 0.2351, 0.3910]])

In [ ]:
#shapes for matrix multiplicaiotn
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

In [ ]:
#torch.matmul(tensor_A, tensor_B)

In [ ]:
#to fix out the tensor shape issue we use transponse
tensor_B.T, tensor_B

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [ ]:
#shapes for matrix multiplicaiotn
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A.float() # Convert tensor_A to float type
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
A = torch.arange(0,100, 7)
A
print(f"type: {A.dtype}")

type: torch.int64


In [ ]:
torch.min(A), A.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(A), A.max()

(tensor(98), tensor(98))

In [ ]:
print(f"A type: {A.dtype}")
torch.mean(A.type(torch.float32)), A.type(torch.float32).mean()

A type: torch.int64


(tensor(49.), tensor(49.))

In [ ]:
torch.sum(A), A.sum()

(tensor(735), tensor(735))

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#adding an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack
x_stacked = torch.vstack([x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x = torch.zeros(2,1,1)
x_squeed = torch.squeeze(x)
x, x.shape, x_squeed.shape


(tensor([[[0.]],
 
         [[0.]]]),
 torch.Size([2, 1, 1]),
 torch.Size([2]))

In [ ]:
x_unsqeezed = torch.unsqueeze(x_squeed, dim=1)
x_unsqeezed, x_unsqeezed.shape

(tensor([[0.],
         [0.]]),
 torch.Size([2, 1]))

In [ ]:
B = torch.randn(2,3,5)
B, B.size()

(tensor([[[-0.4974,  0.4396, -0.7581,  1.0783,  0.8008],
          [ 1.6806,  0.3559, -0.6866,  0.6105,  1.3347],
          [-0.2316,  0.0418, -0.2516,  0.8599, -0.9138]],
 
         [[-0.6581,  0.0780,  0.5258, -0.4880,  1.1914],
          [-0.8140, -0.7360, -1.4032,  0.0360, -0.0635],
          [ 0.6756, -0.0978,  1.8446, -1.1845,  1.3835]]]),
 torch.Size([2, 3, 5]))

In [ ]:
B_permute = torch.permute(B, (1, 2, 0))
B_permute, B_permute.size()

(tensor([[[-0.4974, -0.6581],
          [ 0.4396,  0.0780],
          [-0.7581,  0.5258],
          [ 1.0783, -0.4880],
          [ 0.8008,  1.1914]],
 
         [[ 1.6806, -0.8140],
          [ 0.3559, -0.7360],
          [-0.6866, -1.4032],
          [ 0.6105,  0.0360],
          [ 1.3347, -0.0635]],
 
         [[-0.2316,  0.6756],
          [ 0.0418, -0.0978],
          [-0.2516,  1.8446],
          [ 0.8599, -1.1845],
          [-0.9138,  1.3835]]]),
 torch.Size([3, 5, 2]))

In [ ]:
B[0,0,0] = 123
B[0,0,0], B_permute[0,0,0]

(tensor(123.), tensor(123.))

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
import torch
import numpy as np

In [ ]:
array = np.arange(1.0, 8.0)
print(array)
# from numpy to tensor
tensor = torch.from_numpy(array).type(torch.float32)
print(tensor.dtype)

[1. 2. 3. 4. 5. 6. 7.]
torch.float32


In [ ]:
array = array + 1
array

array([2., 3., 4., 5., 6., 7., 8.])

In [ ]:
array, tensor # tensor is stored separately

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#from tensor to numpy
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Reproducibility (trying to take random out of random)
torch.manual_seed(42)
random_tennsor_1 = torch.rand(3,3)
torch.manual_seed(42)
random_tensor_2 = torch.rand(3,3)
random_tennsor_1, random_tensor_2

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]))

In [ ]:
!nvidia-smi

Fri Apr  3 23:05:26 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor.numpy()

array([1, 2, 3])

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_on_gpu.to("cpu").numpy()

array([1, 2, 3])

In [ ]:
tensor_on_cpu = tensor.to("cpu")
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))